config:
  info: "mainr branch,springcloud-config/config-dev.yml version=4"
#applicaiton.yml是用户级的资源配置项,bootstrap.yml是系统级的，优先级更加高

server:
  port: 3355

spring:
  application:
    name: config-client
  cloud:
    #Config客户端配置
    config:
      label: main #分支名称
      name: config #配置文件名称
      profile: dev #读取后缀名称   上述3个综合：master分支上config-dev.yml的配置文件被读取http://config-3344.com:3344/master/config-dev.yml
      uri: http://localhost:3344 #配置中心地址k

  #15672是WEB管理界面的端口，5762是MQ访问的端口
  rabbitmq:
    host: 192.168.253.129
    port: 5672
    username: admin
    password: admin
    virtual-host: /


#服务注册到Eureka
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:7001/eureka #单机
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka #集群\

#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

